2021-10-29 16:05:14,426     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test1
2021-10-29 16:05:14,426     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test2
2021-10-29 16:05:14,441     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test3
2021-10-29 16:05:16,473     CRITICAL   client.py               Не удалось подключиться к серверу 127.0.0.1:7777, конечный компьютер отверг запрос на подключение.
2021-10-29 16:05:16,473     CRITICAL   client.py               Не удалось подключиться к серверу 127.0.0.1:7777, конечный компьютер отверг запрос на подключение.
2021-10-29 16:06:13,498     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test1
2021-10-29 16:06:13,498     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test2
2021-10-29 16:06:13,513     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test3
2021-10-29 16:06:15,514     CRITICAL   client.py               Не удалось подключиться к серверу 127.0.0.1:7777, конечный компьютер отверг запрос на подключение.
2021-10-29 16:06:15,529     CRITICAL   client.py               Не удалось подключиться к серверу 127.0.0.1:7777, конечный компьютер отверг запрос на подключение.
2021-10-29 16:22:07,614     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test1
2021-10-29 16:22:09,677     CRITICAL   client.py               Не удалось подключиться к серверу 127.0.0.1:7777, конечный компьютер отверг запрос на подключение.
2021-10-29 17:04:48,989     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test1
2021-10-29 17:04:48,990     DEBUG      client.py               Была вызвана функция 'create_presence' c параметрами ('test1',), {}. Вызов из модуля __main__.
2021-10-29 17:04:48,990     DEBUG      client.py               Была вызвана функция 'send_message' c параметрами (<socket.socket fd=300, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50084), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1635516288.9905186, 'user': {'account_name': 'test1'}}), {}. Вызов из модуля common.utils.
2021-10-29 17:04:49,002     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test2
2021-10-29 17:04:49,002     DEBUG      client.py               Была вызвана функция 'create_presence' c параметрами ('test2',), {}. Вызов из модуля __main__.
2021-10-29 17:04:49,003     DEBUG      client.py               Была вызвана функция 'send_message' c параметрами (<socket.socket fd=276, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50085), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1635516289.0025206, 'user': {'account_name': 'test2'}}), {}. Вызов из модуля common.utils.
2021-10-29 17:04:49,008     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test3
2021-10-29 17:04:49,008     DEBUG      client.py               Была вызвана функция 'create_presence' c параметрами ('test3',), {}. Вызов из модуля __main__.
2021-10-29 17:04:49,008     DEBUG      client.py               Была вызвана функция 'send_message' c параметрами (<socket.socket fd=476, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50086), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1635516289.008522, 'user': {'account_name': 'test3'}}), {}. Вызов из модуля common.utils.
2021-10-29 17:04:49,019     DEBUG      client.py               Была вызвана функция 'get_message' c параметрами (<socket.socket fd=300, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50084), raddr=('127.0.0.1', 7777)>,), {}. Вызов из модуля common.utils.
2021-10-29 17:04:49,019     DEBUG      client.py               Была вызвана функция 'process_response_ans' c параметрами ({'response': 200},), {}. Вызов из модуля __main__.
2021-10-29 17:04:49,019     INFO       client.py               Установлено соединение с сервером. Ответ сервера: 200 : OK
2021-10-29 17:04:49,019     DEBUG      client.py               Была вызвана функция 'create_connect_client' c параметрами (), {}. Вызов из модуля __main__.
2021-10-29 17:04:49,020     DEBUG      client.py               Клиентские процессы запущены
2021-10-29 17:04:49,028     DEBUG      client.py               Была вызвана функция 'get_message' c параметрами (<socket.socket fd=276, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50085), raddr=('127.0.0.1', 7777)>,), {}. Вызов из модуля common.utils.
2021-10-29 17:04:49,028     DEBUG      client.py               Была вызвана функция 'process_response_ans' c параметрами ({'response': 200},), {}. Вызов из модуля __main__.
2021-10-29 17:04:49,028     INFO       client.py               Установлено соединение с сервером. Ответ сервера: 200 : OK
2021-10-29 17:04:49,028     DEBUG      client.py               Была вызвана функция 'create_connect_client' c параметрами (), {}. Вызов из модуля __main__.
2021-10-29 17:04:49,029     DEBUG      client.py               Клиентские процессы запущены
2021-10-29 17:04:49,039     DEBUG      client.py               Была вызвана функция 'get_message' c параметрами (<socket.socket fd=476, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50086), raddr=('127.0.0.1', 7777)>,), {}. Вызов из модуля common.utils.
2021-10-29 17:04:49,039     DEBUG      client.py               Была вызвана функция 'process_response_ans' c параметрами ({'response': 200},), {}. Вызов из модуля __main__.
2021-10-29 17:04:49,039     INFO       client.py               Установлено соединение с сервером. Ответ сервера: 200 : OK
2021-10-29 17:04:49,039     DEBUG      client.py               Была вызвана функция 'create_connect_client' c параметрами (), {}. Вызов из модуля __main__.
2021-10-29 17:04:49,040     DEBUG      client.py               Клиентские процессы запущены
2021-10-29 17:05:18,383     DEBUG      client.py               Была вызвана функция 'send_message' c параметрами (<socket.socket fd=476, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50086), raddr=('127.0.0.1', 7777)>, {'action': 'm-', 'from': 'test3', 'to': 'test2', 'time': 1635516318.3833926, 'mess_text': 'dhfdjfh'}), {}. Вызов из модуля common.utils.
2021-10-29 17:05:18,383     INFO       client.py               Отправлено сообщение для пользователя test2.
2021-10-29 17:05:18,384     DEBUG      client.py               Была вызвана функция 'create_message' c параметрами (<ClientManage(Thread-2, started daemon 9576)>, <socket.socket fd=476, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50086), raddr=('127.0.0.1', 7777)>, 'test3'), {}. Вызов из модуля __main__.
2021-10-29 17:05:18,467     DEBUG      client.py               Была вызвана функция 'get_message' c параметрами (<socket.socket fd=276, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50085), raddr=('127.0.0.1', 7777)>,), {}. Вызов из модуля common.utils.
2021-10-29 17:05:18,468     INFO       client.py               Получено сообщение от пользователя test3:
dhfdjfh
2021-10-29 17:05:36,062     DEBUG      client.py               Была вызвана функция 'create_exit_message' c параметрами (<ClientManage(Thread-2, started daemon 9576)>, 'test3'), {}. Вызов из модуля __main__.
2021-10-29 17:05:36,062     DEBUG      client.py               Была вызвана функция 'send_message' c параметрами (<socket.socket fd=476, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50086), raddr=('127.0.0.1', 7777)>, {'action': 'exit', 'time': 1635516336.0620773, 'account_name': 'test3'}), {}. Вызов из модуля common.utils.
2021-10-29 17:05:36,062     INFO       client.py               Завершение работы по команде пользователя.
2021-10-29 17:05:36,198     ERROR      client.py               Потеряно соединение с сервером
2021-10-29 17:05:47,992     DEBUG      client.py               Была вызвана функция 'create_exit_message' c параметрами (<ClientManage(Thread-2, started daemon 7736)>, 'test2'), {}. Вызов из модуля __main__.
2021-10-29 17:05:47,992     DEBUG      client.py               Была вызвана функция 'send_message' c параметрами (<socket.socket fd=276, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50085), raddr=('127.0.0.1', 7777)>, {'action': 'exit', 'time': 1635516347.9923546, 'account_name': 'test2'}), {}. Вызов из модуля common.utils.
2021-10-29 17:05:47,992     INFO       client.py               Завершение работы по команде пользователя.
2021-10-29 17:05:48,384     ERROR      client.py               Потеряно соединение с сервером
2021-10-29 17:05:48,504     DEBUG      threading.py            Была вызвана функция 'run' c параметрами (<ClientManage(Thread-2, started daemon 7736)>,), {}. Вызов из модуля __main__.
2021-10-29 20:22:05,827     INFO       client.py               Запущен клиент с парамертами: адрес сервера: 127.0.0.1, порт: 7777, имя пользователя: test
2021-10-29 20:22:05,827     DEBUG      client.py               Была вызвана функция 'create_presence' c параметрами ('test',), {}. Вызов из модуля __main__.
2021-10-29 20:22:05,827     DEBUG      client.py               Была вызвана функция 'send_message' c параметрами (<socket.socket fd=388, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50422), raddr=('127.0.0.1', 7777)>, {'action': 'presence', 'time': 1635528125.8278093, 'user': {'account_name': 'test'}}), {}. Вызов из модуля common.utils.
2021-10-29 20:22:06,311     DEBUG      client.py               Была вызвана функция 'get_message' c параметрами (<socket.socket fd=388, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50422), raddr=('127.0.0.1', 7777)>,), {}. Вызов из модуля common.utils.
2021-10-29 20:22:06,311     DEBUG      client.py               Была вызвана функция 'process_response_ans' c параметрами ({'response': 200},), {}. Вызов из модуля __main__.
2021-10-29 20:22:06,311     INFO       client.py               Установлено соединение с сервером. Ответ сервера: 200 : OK
2021-10-29 20:22:06,311     DEBUG      client.py               Была вызвана функция 'create_connect_client' c параметрами (), {}. Вызов из модуля __main__.
2021-10-29 20:22:06,311     DEBUG      client.py               Клиентские процессы запущены
2021-10-29 20:24:48,595     DEBUG      client.py               Была вызвана функция 'send_message' c параметрами (<socket.socket fd=388, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50422), raddr=('127.0.0.1', 7777)>, {'action': 'm-', 'from': 'test', 'to': 'test1', 'time': 1635528288.5958326, 'mess_text': 'Рома. Ты сделал уроки?'}), {}. Вызов из модуля common.utils.
2021-10-29 20:24:48,595     INFO       client.py               Отправлено сообщение для пользователя test1.
2021-10-29 20:24:48,595     DEBUG      client.py               Была вызвана функция 'create_message' c параметрами (<ClientManage(Thread-2, started daemon 3316)>, <socket.socket fd=388, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50422), raddr=('127.0.0.1', 7777)>, 'test'), {}. Вызов из модуля __main__.
2021-10-29 20:25:43,937     DEBUG      client.py               Была вызвана функция 'get_message' c параметрами (<socket.socket fd=388, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50422), raddr=('127.0.0.1', 7777)>,), {}. Вызов из модуля common.utils.
2021-10-29 20:25:43,937     INFO       client.py               Получено сообщение от пользователя test1:
Нет
2021-10-29 20:26:24,904     DEBUG      client.py               Была вызвана функция 'send_message' c параметрами (<socket.socket fd=388, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50422), raddr=('127.0.0.1', 7777)>, {'action': 'm-', 'from': 'test', 'to': 'test1', 'time': 1635528384.9045324, 'mess_text': 'Удивительно'}), {}. Вызов из модуля common.utils.
2021-10-29 20:26:24,904     INFO       client.py               Отправлено сообщение для пользователя test1.
2021-10-29 20:26:24,904     DEBUG      client.py               Была вызвана функция 'create_message' c параметрами (<ClientManage(Thread-2, started daemon 3316)>, <socket.socket fd=388, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50422), raddr=('127.0.0.1', 7777)>, 'test'), {}. Вызов из модуля __main__.
